---
- hosts: all

  vars:
    cap_file: web_{{ ansible_hostname }}_{{ ansible_date_time['epoch'] }}.pcap
    server_port: 8080

  tasks:
    - name: Install python and tcpdump
      become: yes
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - python3
        - tcpdump

    - name: Adjust arp table
      command: arp -i eth1 -s 192.168.56.101 080088112211
      become: yes

    - name: Start file server using Python HTTP server
      command: >
        python3 -m http.server 8080
        --directory /vagrant/test_files
      async: 7200
      poll: 0
      register: server_process
      changed_when: false

    - name: create pcap dir
      file:
        path: "/vagrant/pcap"
        state: directory
        mode: "0755"
      become: yes

    - name: start tcpdump
      command: tcpdump -i eth1 -w /vagrant/pcap/{{ cap_file }} src host 192.168.56.102
      async: 7200
      poll: 0
      changed_when: false
      become: yes

    - name: Wait for server to start
      wait_for:
        port: "{{ server_port }}"
        host: "{{ ansible_default_ipv4.address }}"
        delay: 2
        timeout: 30
