- name: Configure web client
  hosts: client
  become: yes

  tasks:
    - name: Install curl and tcpdump
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - curl
        - tcpdump

    - name: Copy bot script
      copy:
        src: ./bot.sh
        dest: /tmp/
        mode: '755'
