- name: Configure web server
  hosts: server
  become: yes

  tasks:
    - name: Install git
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - git

    - name: Clone web server repo
      become: no
      git:
        repo: 'https://gitlab.com/icaroo/web-rand'
        dest: /tmp/web-server
        version: main
        clone: yes
        update: yes 

