- name: Configure web server
  hosts: server
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Assert nginx instance
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copy HTML files
      copy:
        src: ./web-server/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
