- name: Configure web server
  hosts: server
  become: yes

  tasks:
    - name: Install ffmpeg
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - ffmpeg

    - name: Execute Server script
      script: ./server.sh
      async: 1000
      poll: 5
