- name: Configure web server
  hosts: server
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - nginx

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes
