---
- hosts: all

  vars:
    server_port: 8080
    test_file: png_500MB.png

  tasks:
    - name: Install python
      become: yes
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - python3

    - name: Adjust arp table
      command: arp -i eth1 -s 192.168.56.101 080088112211
      become: yes

    - name: Start file server using Python HTTP server
      command: >
        python3 -m http.server 8080
        --directory /vagrant/test_files
      async: 3600
      poll: 0
      register: server_process
      changed_when: false

    - name: Wait for server to start
      wait_for:
        port: "{{ server_port }}"
        host: "{{ ansible_default_ipv4.address }}"
        delay: 2
        timeout: 30

    - name: Display server information
      debug:
        msg: |
          File server started on http://192.168.56.102:{{ server_port }}
          Test file: {{ test_file }}
