---
- hosts: all

  tasks:
    - name: Install python-Scapy and dependencies
      apt: name={{ item }} update_cache=yes
      loop: ["python3-scapy", "net-tools"]
      become: yes
    - name: Adjust arp table
      command: arp -i eth1 -s 192.168.56.101 080088112211
      become: yes
